export const ERROR_MESSAGE = {
    unknown: "Unknown error",
    NetworkError: "Network error",
    BadRequest: "Bad request",
    Unauthorized: "Unauthorized access",
    Forbidden: "Forbidden",
    NotFound: "Resource not found",
    InternalServerError: "Internal server error",
    ServiceUnavailable: "Service unavailable",
    TokenRefreshError: "Не удалось обновить токен",
    TokenRefreshErrorDetailed: "Ошибка при обновлении токена:",
    TokenError: "Token error",
    SESSION_NOT_FOUND: 'Не удалось получить данные сессии',
    SESSION_NOT_FOUND_DETAILLED: 'Произошла ошибка при получении данных сессии',
    FILE_NOT_FOUND: 'Не удалось получить URL файла',
    FILE_ERROR: 'Произошла ошибка при экспорте отчета',
    STAFF_SESSION_ERROR: 'Произошла ошибка при получении данных сессии сотрудника',
    PROVIDER_ERROR: 'useUser должен использоваться внутри UserProvider',
    USER_CONTEXT_ERROR_DETAILLED: 'Ошибка при получении данных пользователя:',
    LoginError: 'Ошибка при авторизации',
    LogoutError: 'Ошибка при выходе',
    SessionContextError: 'useLocalSession должен использоваться внутри LocalSessionProvider',
};
