export const ROUTES = {
    home: "/",
    signIn: "/sign-in",
    signUp: "/sign-up",
    createStaff: "/staff/create",
    staff: "/staff",
    staffEdit: (id: string) => `/staff/${id}`,
    rolesEdit: (id: string) => `/roles/${id}`,
    createRole: "/roles/create",
    roles: "/roles",
    permission: "/permissions",
    createPermission: "/permissions/create",
    editPermission: (id: string) => `/permissions/${id}`,
    patients: "/patients",
    createPatient: "/patients/create",
    editPatient: (id: string) => `/patients/${id}`,
    appointments: "/appointments",
    createAppointment: "/appointments/create",
    editAppointment: (id: string) => `/appointments/${id}`,
    filials: "/filials",
    createFilial: "/filials/create",
    editFilial: (id: string) => `/filials/${id}`,
    expenseCategories: "/expense-categories",
    createExpenseCategory: "/expense-categories/create",
    editExpenseCategory: (id: string) => `/expense-categories/${id}`,
    services: "/services",
    createService: "/services/create",
    editService: (id: string) => `/services/${id}`,
    expenses: "/expenses",
    createExpense: "/expenses/create",
    editExpense: (id: string) => `/expenses/${id}`,
    createSpecialist: "/specialist/create",
    specialists: "/specialist",
    specialistEdit: (id: string) => `/specialist/${id}`,
};
